[mypy] # global options
# third-party scientific packages ship no type stubs / py.typed marker
ignore_missing_imports = True
# add this to find packages without an __init__.py file
namespace_packages = True
strict_optional = True
no_implicit_optional = True
disallow_untyped_defs = True
