[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyRCN"
dynamic = ["version"]
description = "A scikit-learn-compatible framework for Reservoir Computing in Python"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name="Peter Steiner", email="peter.steiner@pyrcn.net" },
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dependencies = [
    "scikit-learn>=1.6",
    "numpy>=1.18.1",
    "scipy>=1.4.0",
    "joblib>=0.13.2",
    "pandas>=1.0.0",
]

[project.optional-dependencies]
test = [
    "pytest>=6.5.0",
    "pytest-cov",
    "pytest-mypy",
    "mypy",
    "flake8",
]
examples = [
    "matplotlib",
    "seaborn",
    "ipywidgets",
    "ipympl",
    "tqdm",
]

[project.urls]
Homepage = "https://pyrcn.net/"
Documentation = "https://pyrcn.readthedocs.io/"
Source = "https://github.com/PlasmaControl/PyRCN/"
Issues = "https://github.com/PlasmaControl/PyRCN/issues"

[tool.setuptools.dynamic]
version = { attr = "pyrcn._version.__version__" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
